import { GoogleContact, CalendarEvent, Domicile } from './types';

export const INITIAL_CONTACTS: GoogleContact[] = [
  {
    id: 'c1',
    name: 'Maria Aparecida da Silva',
    cns: '700123456789012',
    cpf: '123.456.789-00',
    birthDate: '1988-04-12',
    gender: 'F',
    motherName: 'Joana da Silva',
    email: 'maria.aparecida@email.com',
    phone: '(11) 98765-4321',
    address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Gestante', 'Microárea 02 - Rosa 🔴', 'Bolsa Família'],
    notes: 'Gestante de alto risco (28 semanas). Pré-natal em dia na USF Bela Vista.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    lat: -23.5614,
    lng: -46.6559,
    domicileId: 'dom1',
    familyRelationship: 'Responsável Familiar',
    isHeadOfHousehold: true,
    healthProfile: {
      isPregnant: true,
      gestationalAgeWeeks: 28,
      isHypertensive: true,
      isDiabetic: false,
      isBedridden: false,
      isElderly: false,
      isChildUnder2: false,
      isVaccinationUpToDate: true,
      notes: 'Verificar pressão arterial na visita e agendar ultrassom de 3º trimestre.'
    }
  },
  {
    id: 'c2',
    name: 'José Carlos da Silva',
    cns: '700987654321098',
    cpf: '234.567.890-11',
    birthDate: '1985-09-20',
    gender: 'M',
    motherName: 'Francisca da Silva',
    email: 'jose.carlos@email.com',
    phone: '(11) 97654-3210',
    address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Hipertenso', 'Microárea 02 - Rosa 🔴', 'Trabalhador Autônomo'],
    notes: 'Esposo de Maria Aparecida. Faz uso contínuo de Losartana 50mg.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    lat: -23.5614,
    lng: -46.6559,
    domicileId: 'dom1',
    familyRelationship: 'Cônjuge / Companheiro(a)',
    isHeadOfHousehold: false,
    healthProfile: {
      isPregnant: false,
      isHypertensive: true,
      isDiabetic: false,
      isBedridden: false,
      isElderly: false,
      isChildUnder2: false,
      isVaccinationUpToDate: true,
      notes: 'Aferição periódica de PA. Receita de medicação atualizada.'
    }
  },
  {
    id: 'c3',
    name: 'Lucas Gabriel da Silva',
    cns: '700555444333222',
    cpf: '555.444.333-22',
    birthDate: '2024-02-10',
    gender: 'M',
    motherName: 'Maria Aparecida da Silva',
    phone: '(11) 98765-4321',
    address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Criança (0-2a)', 'Microárea 02 - Rosa 🔴', 'Acompanhamento Puericultura'],
    notes: 'Filho de Maria e José. Vacinação em dia. Peso e estatura no percentil ideal.',
    avatarUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=150',
    lat: -23.5614,
    lng: -46.6559,
    domicileId: 'dom1',
    familyRelationship: 'Filho(a)',
    isHeadOfHousehold: false,
    healthProfile: {
      isPregnant: false,
      isHypertensive: false,
      isDiabetic: false,
      isBedridden: false,
      isElderly: false,
      isChildUnder2: true,
      isVaccinationUpToDate: true,
      notes: 'Verificar cartão de vacinas (Penta e VIP de 6 meses).'
    }
  },
  {
    id: 'c4',
    name: 'Dona Antônia Santos Oliveira',
    cns: '700333222111000',
    cpf: '345.678.901-22',
    birthDate: '1947-11-05',
    gender: 'F',
    motherName: 'Luzia Santos',
    email: 'antonia.santos@email.com',
    phone: '(11) 96543-2109',
    address: 'Rua Augusta, 1500 - Consolação, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Hipertenso', 'Diabético', 'Acamado', 'Microárea 02 - Rosa 🔴', 'Prioridade'],
    notes: 'Idosa acamada por sequela de AVC. Necessita de curativo periódico e fraldas.',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    lat: -23.5558,
    lng: -46.6575,
    domicileId: 'dom2',
    familyRelationship: 'Responsável Familiar',
    isHeadOfHousehold: true,
    healthProfile: {
      isPregnant: false,
      isHypertensive: true,
      isDiabetic: true,
      isBedridden: true,
      isElderly: true,
      isChildUnder2: false,
      isVaccinationUpToDate: true,
      hasSpecialNeeds: true,
      notes: 'Visita semanal com equipe de enfermagem para acompanhamento de lesão de pele.'
    }
  },
  {
    id: 'c5',
    name: 'Roberto Alencar de Souza',
    cns: '700444333222111',
    cpf: '456.789.012-33',
    birthDate: '1962-07-15',
    gender: 'M',
    motherName: 'Lourdes Alencar',
    email: 'roberto.alencar@email.com',
    phone: '(11) 95432-1098',
    address: 'Rua Teodoro Sampaio, 800 - Pinheiros, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Hipertenso', 'Diabético', 'Microárea 02 - Rosa 🔴'],
    notes: 'Paciente diabético com medicação oral (Metformina) e acompanhamento trimestral de glicada.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    lat: -23.5592,
    lng: -46.6775,
    domicileId: 'dom3',
    familyRelationship: 'Responsável Familiar',
    isHeadOfHousehold: true,
    healthProfile: {
      isPregnant: false,
      isHypertensive: true,
      isDiabetic: true,
      isBedridden: false,
      isElderly: true,
      isChildUnder2: false,
      isVaccinationUpToDate: true,
      notes: 'HGT de rotina e orientação para atividade física comunitária.'
    }
  },
  {
    id: 'c6',
    name: 'Fernanda Lima de Souza',
    cns: '700888777666555',
    cpf: '567.890.123-44',
    birthDate: '1995-03-25',
    gender: 'F',
    motherName: 'Clarice Lima',
    email: 'fernanda.lima@email.com',
    phone: '(11) 94321-0987',
    address: 'Rua Teodoro Sampaio, 800 - Pinheiros, São Paulo - SP',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    labels: ['Gestante', 'Microárea 02 - Rosa 🔴'],
    notes: 'Filha de Roberto. Gestante de 14 semanas. Primeira gestação.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    lat: -23.5592,
    lng: -46.6775,
    domicileId: 'dom3',
    familyRelationship: 'Filho(a)',
    isHeadOfHousehold: false,
    healthProfile: {
      isPregnant: true,
      gestationalAgeWeeks: 14,
      isHypertensive: false,
      isDiabetic: false,
      isBedridden: false,
      isElderly: false,
      isChildUnder2: false,
      isVaccinationUpToDate: true,
      notes: 'Entregue cartão de gestante. Próxima consulta dia 10 na USF.'
    }
  }
];

export const INITIAL_DOMICILES: Domicile[] = [
  {
    id: 'dom1',
    street: 'Av. Paulista',
    number: '1000',
    complement: 'Apto 42',
    neighborhood: 'Bela Vista',
    zipCode: '01310-100',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    residenceType: 'Apartamento',
    ownership: 'Alugado',
    waterSupply: 'Rede Encanada',
    sanitation: 'Rede Pública',
    garbageCollection: 'Coletado',
    hasElectricity: true,
    hasPets: true,
    petsDetail: '1 gato vacinado',
    lat: -23.5614,
    lng: -46.6559,
    notes: 'Família receptiva. Acesso por elevador.',
    createdAt: '2025-01-15',
    familyMembers: [
      {
        patientId: 'c1',
        patientName: 'Maria Aparecida da Silva',
        relationship: 'Responsável Familiar',
        isHeadOfHousehold: true,
        cns: '700123456789012',
        birthDate: '1988-04-12',
        phone: '(11) 98765-4321'
      },
      {
        patientId: 'c2',
        patientName: 'José Carlos da Silva',
        relationship: 'Cônjuge / Companheiro(a)',
        isHeadOfHousehold: false,
        cns: '700987654321098',
        birthDate: '1985-09-20',
        phone: '(11) 97654-3210'
      },
      {
        patientId: 'c3',
        patientName: 'Lucas Gabriel da Silva',
        relationship: 'Filho(a)',
        isHeadOfHousehold: false,
        cns: '700555444333222',
        birthDate: '2024-02-10',
        phone: '(11) 98765-4321'
      }
    ]
  },
  {
    id: 'dom2',
    street: 'Rua Augusta',
    number: '1500',
    complement: 'Casa 1',
    neighborhood: 'Consolação',
    zipCode: '01305-100',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    residenceType: 'Casa',
    ownership: 'Próprio',
    waterSupply: 'Rede Encanada',
    sanitation: 'Rede Pública',
    garbageCollection: 'Coletado',
    hasElectricity: true,
    hasPets: false,
    lat: -23.5558,
    lng: -46.6575,
    notes: 'Residência com rampa de acesso para idosa acamada.',
    createdAt: '2025-01-20',
    familyMembers: [
      {
        patientId: 'c4',
        patientName: 'Dona Antônia Santos Oliveira',
        relationship: 'Responsável Familiar',
        isHeadOfHousehold: true,
        cns: '700333222111000',
        birthDate: '1947-11-05',
        phone: '(11) 96543-2109'
      }
    ]
  },
  {
    id: 'dom3',
    street: 'Rua Teodoro Sampaio',
    number: '800',
    complement: 'Sobrado',
    neighborhood: 'Pinheiros',
    zipCode: '05406-000',
    city: 'São Paulo',
    state: 'SP',
    microarea: 'Microárea 02 - Rosa 🔴',
    residenceType: 'Casa',
    ownership: 'Próprio',
    waterSupply: 'Rede Encanada',
    sanitation: 'Rede Pública',
    garbageCollection: 'Coletado',
    hasElectricity: true,
    hasPets: true,
    petsDetail: '2 cachorros pequeno porte',
    lat: -23.5592,
    lng: -46.6775,
    notes: 'Campainha com defeito, chamar no portão.',
    createdAt: '2025-02-01',
    familyMembers: [
      {
        patientId: 'c5',
        patientName: 'Roberto Alencar de Souza',
        relationship: 'Responsável Familiar',
        isHeadOfHousehold: true,
        cns: '700444333222111',
        birthDate: '1962-07-15',
        phone: '(11) 95432-1098'
      },
      {
        patientId: 'c6',
        patientName: 'Fernanda Lima de Souza',
        relationship: 'Filho(a)',
        isHeadOfHousehold: false,
        cns: '700888777666555',
        birthDate: '1995-03-25',
        phone: '(11) 94321-0987'
      }
    ]
  }
];

const getTodayStr = (): string => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const getInitialEvents = (): CalendarEvent[] => {
  const today = getTodayStr();

  return [
    {
      id: 'ev1',
      title: 'Visita Domiciliar - Acompanhamento Gestante & Puericultura',
      contactId: 'c1',
      contactName: 'Maria Aparecida da Silva',
      domicileId: 'dom1',
      phone: '(11) 98765-4321',
      address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
      city: 'São Paulo',
      lat: -23.5614,
      lng: -46.6559,
      startTime: '08:30',
      endTime: '09:30',
      date: today,
      visitReason: 'Acompanhamento Gestante (28 sem) e Puericultura Lucas',
      description: 'Aferição de PA da gestante, orientação sobre exames do 3º trimestre e checagem da carteira de vacinas do bebê.',
      status: 'realizada',
      observation: 'PA 120/80 mmHg. Queixa de edema em MMII. Orientações de repouso passadas. Carteira do bebê 100% atualizada.',
      updatedAt: '09:25'
    },
    {
      id: 'ev2',
      title: 'Visita Domiciliar - Curativo e Acompanhamento Acamado',
      contactId: 'c4',
      contactName: 'Dona Antônia Santos Oliveira',
      domicileId: 'dom2',
      phone: '(11) 96543-2109',
      address: 'Rua Augusta, 1500 - Consolação, São Paulo - SP',
      city: 'São Paulo',
      lat: -23.5558,
      lng: -46.6575,
      startTime: '10:00',
      endTime: '11:00',
      date: today,
      visitReason: 'Busca Ativa / Paciente Acamado & Diabético',
      description: 'Avaliação de integridade cutânea, entrega de fraldas descartáveis geriatria e verificação de HGT.',
      status: 'pendente',
      observation: '',
      updatedAt: ''
    },
    {
      id: 'ev3',
      title: 'Visita Domiciliar - Acompanhamento Hipertensão e Diabetes',
      contactId: 'c5',
      contactName: 'Roberto Alencar de Souza',
      domicileId: 'dom3',
      phone: '(11) 95432-1098',
      address: 'Rua Teodoro Sampaio, 800 - Pinheiros, São Paulo - SP',
      city: 'São Paulo',
      lat: -23.5592,
      lng: -46.6775,
      startTime: '11:30',
      endTime: '12:30',
      date: today,
      visitReason: 'Controle de Hipertensão (HAS) e Diabetes (DM)',
      description: 'Aferição de PA, glicemia de jejum e verificação da medicação de uso contínuo.',
      status: 'pendente',
      observation: '',
      updatedAt: ''
    },
    {
      id: 'ev4',
      title: 'Visita Domiciliar - Atualização de Cadastro Domiciliar e Pré-Natal',
      contactId: 'c6',
      contactName: 'Fernanda Lima de Souza',
      domicileId: 'dom3',
      phone: '(11) 94321-0987',
      address: 'Rua Teodoro Sampaio, 800 - Pinheiros, São Paulo - SP',
      city: 'São Paulo',
      lat: -23.5592,
      lng: -46.6775,
      startTime: '14:00',
      endTime: '15:00',
      date: today,
      visitReason: 'Acompanhamento Gestante de Primeira Consulta (14 sem)',
      description: 'Orientação sobre pré-natal na USF, entrega do cartão da gestante e suplementação de Ácido Fólico / Sulfato Ferroso.',
      status: 'pendente',
      observation: '',
      updatedAt: ''
    }
  ];
};
